name: HappyKeyTone
options:
  bundleIdPrefix: com.happykeytone
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "15.4"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    ENABLE_HARDENED_RUNTIME: true
    SWIFT_STRICT_CONCURRENCY: complete
    DEVELOPMENT_TEAM: S555TC8ECE
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "Apple Development"
      CODE_SIGN_STYLE: Automatic
    Release:
      CODE_SIGN_IDENTITY: "Developer ID Application"
      CODE_SIGN_STYLE: Manual
      OTHER_CODE_SIGN_FLAGS: "--timestamp"
      CODE_SIGN_INJECT_BASE_ENTITLEMENTS: false

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    version: 2.8.1

targets:
  HappyKeyTone:
    type: application
    platform: macOS
    sources:
      - path: HappyKeyTone/Sources
      - path: HappyKeyTone/Resources/Assets.xcassets
      - path: HappyKeyTone/Resources/SoundPacks
        type: folder
        buildPhase: resources
    dependencies:
      - package: Sparkle
        product: Sparkle
    settings:
      base:
        INFOPLIST_FILE: HappyKeyTone/Info.plist
        CODE_SIGN_ENTITLEMENTS: HappyKeyTone/HappyKeyTone.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.happykeytone.app
        PRODUCT_NAME: HappyKeyTone
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "3"
    info:
      path: HappyKeyTone/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright 2026 HappyKeyTone. All rights reserved."
        SUFeedURL: "https://raw.githubusercontent.com/studiodog1108/HappyKeyTone/main/appcast.xml"
        SUPublicEDKey: "K6ILHMxqI6jjI4XuF9FixaF0idatQ6pUfnPMZnsfhSM="
        SUEnableAutomaticChecks: true
        SUScheduledCheckInterval: 86400
